### ISSUE TITLE
How should we pre-pend attributes?

### ISSUE THREAD

**Issue by matthew-dean** [idmadj/ga-gtag#10]
For something like adding consent flags, they must be added before the script is installed. See: https://developers.google.com/tag-platform/devguides/consent

However, I don't really see how this script would work if one needed to add those options before script-loading.

**Comment by idmadj** [comment]
Hi, sorry for the super long wait!

If you still need it, I've just added the option to pre-emptively define `window.dataLayer`:
```js
import { gtag, initDataLayer, install } from 'ga-gtag';

initDataLayer();
gtag('consent', 'default', {
  'ad_storage': 'denied',
  'analytics_storage': 'denied'
});
install('G-##########');
```
