### ISSUE TITLE
Where should we install this for optimal Page Speed?

### ISSUE THREAD

**Issue by BrandonCopley** [idmadj/ga-gtag#5]
Currently we use instal() in useEffect() is this the optimal place to put the install tag?

I am reviewing our page speed insights and it's asking us to "Reduce unused JavaScript and defer loading scripts until they are required to decrease bytes consumed by network activity."

This is the major script in that bucket.

**Comment by idmadj** [comment]
`install()` only needs to be called once in your app's lifetime. If you're using something like create-react-app, this can be in index.js, just before the first call to `ReactDOM.render(...)`

**Comment by BrandonCopley** [comment]
We are wanting to defer this until after the page is loaded.
